sudo: false
language: python
python:
- '3.6'
install:
- pip install -r requirements.txt
- pip install flake8
- pip install python-coveralls
script:
- coverage run --source=rimradio -m unittest tests
- flake8 .
after_success:
- coverage report
- coveralls
